name = "lf-casper"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Casper theme from Ghost Foundation"
homepage = "http://yavor.in"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "Yavor Yankov"
  homepage = "http://yavor.in"

[original]
  name = "Casper"
  author = "Valere JEANTET"
  homepage = "http://vjeantet.fr"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
